services:
  db:
    image: postgres
    container_name: postgres-dwanium
    restart: always
    environment:
      POSTGRES_DB: Dwanium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    image: dwanium 
    container_name: dwanium-c
    env_file:
      - .env
